### PR TITLE
WIP initial local function spike

### PR DESCRIPTION
**Pull request by jchannon**
need to double check the async/await lack of

### CODE REVIEW

**Comment by jchannon** [comment]
After reading a bit of this not sure we save anything in terms of perf https://blogs.msdn.microsoft.com/seteplia/2017/10/03/dissecting-the-local-functions-in-c-7/

**Comment by benaadams** [comment]
> However, saying that we're not capturing arguments 

You are capturing *all* the arguments; but I assume that's the point?

e.g. `handler` and `statusCodeHandlers` are used in the local function `myFunc` without being passed -however its not capturing any more than the closure (lambda) was previously.

**Comment by IEvangelist** [comment]
> Local functions are allocation-free if no conversion to delegates is happening

Your newly added local functions are simply acting as a replacement for the `RequestDelegate`, as a result these is a conversion from the local function to the delegate. This means that there are allocations, and it is not "allocation-free".

**Comment by benaadams** [comment]
Its only creating them on start up though, so allocations shouldn't matter too much?

**Comment by jchannon** [comment]
No not too much. We also have local functions here https://github.com/jchannon/Botwin/blob/master/src/BotwinModule.cs#L32 but again not sure we've gained by having them.

**Comment by benaadams** [comment]
No captures in the example you just linked; a local function would be better - or moving the lambda to a `readonly static`; as while the lambda will be initalized only once it will still be in the method body which will make the method less likely to be an inline candidate due to its size https://github.com/dotnet/roslyn/issues/13624.

A local function will be better than a `readonly static` lambda as it will be created at compile time, while the `readonly static` will be done at runtime.

Doing it at runtime has the issue that the first method calling it will have an initalization check inserted by the Jit to see whether it has already been created; and everything else calling it will be free of that - though the check is pretty minor in the scheme of things.

**Comment by benaadams** [comment]
I might have been wrong: `handler` :-/

**Comment by jchannon** [comment]
wrong about what?

**Comment by benaadams** [comment]
```csharp
protected void Get(string path, Func<HttpRequest, HttpResponse, RouteData, Task> handler)
{
    Task RequestDelegate(HttpContext httpContext) => handler(httpContext.Request, httpContext.Response, httpContext.GetRouteData());
    this.Get(path, RequestDelegate);
}
```
The lambda is capturing `handler`; so you couldn't even move it to a `readonly static`

**Comment by jchannon** [comment]
Brill. Thanks for the help guys. Will close the PR then as it adds no value.

**Pull request closed without merging**
